name: Run Cypress Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Cypress binary
        run: |
          npx cypress install
          chmod -R 755 ./node_modules/cypress
          chmod +x ./node_modules/.bin/cypress

      - name: Run Cypress tests
        run: npx cypress run
